language: node_js
node_js:
  - "stable"

env:
  - PR_COMMENT=false

before_install:
  - npm install -g gulp-cli
  - npm install gulp --save-dev

before_script:
  - npm install
script: gulp serve

  - npm install